### ISSUE TITLE
Targets missing (Visual Studio 2019)

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#30] opened 2020-02-11 19:54 UTC
Hello,

First of all, thank you for your efforts on this extension. It seems very useful and is filling a crippling gap in VS.

I am using Visual Studio, and have a bunch of projects in my solution. Most of them are C# projects, expect one which is C++/CLI. For reference, you can find the code at https://www.github.com/supermemo/SuperMemoAssistant/

When I open MSBuild Task Explorer, there are **no targets listed** under any of the projects. I have attached a picture below.

![MSBuild-Task-Explorer_No-Target-And-Filter-Not-Working-And-Style-Issue](https://user-images.githubusercontent.com/3876562/74273229-5e972280-4d10-11ea-931c-a26534d7fc1e.png)

I will be creating two additional tickets and referencing this one for context.

**Comment by Serg046** [comment] 2020-02-12 07:58
Hmm, I've just checked my c++/cli project and it works fine. However, the thing is that the project is migrated to .net core 3.1, maybe it makes the difference. I will have some time to check all the tickets later, maybe next week.

**Comment by Serg046** [comment] 2020-02-13 15:30
Is that one you mentioned? It works fine for me. Could you check again, ensure the project exists in Solution Explorer and share more info about the versions you use?

![image](https://user-images.githubusercontent.com/4963385/74450141-4e08b880-4e86-11ea-8021-797143688898.png)

**Comment by Serg046** [comment] 2020-02-13 15:33
Aah, you meant the targets themselves. That's because you set some words in search but there is no any "SuperMemo" target.

**Comment by alexis-** [comment] 2020-02-13 15:39
Hello,

Thanks for getting back on this quickly. I sent the original screenshot with a filter so I could demonstrate the three issues at once. However, I did think the filter was meant to search for the project name, not the target. Issue #32 is now irrelevant, you can close it.

However, my issue with missing target persists. **None** of my project has any target, I am afraid. See screenshot below (I set the theme to Light to check if that would make any difference)

![image](https://user-images.githubusercontent.com/3876562/74450731-dedb9600-4e7e-11ea-9d2b-4d8bd10b8053.png)

**Comment by Serg046** [comment] 2020-02-13 15:43
Did you click `Refresh` button? I just want to be sure that the cached search string is not in use. If the issue still exists, please copy everything from `MSBuildTaskExplorer` output window.

**Comment by alexis-** [comment] 2020-02-13 16:04
I did try to refresh several times before, to no avail. I somehow managed (see ** for details)
to get the tasks to appear for a second. However, I immediately received a crash report and MSBuild Task Explorer's window was replaced with the exception message:
```
System.InvalidOperationException: The project provided was not loaded in the collection.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.ProjectCollection.UnloadProject(Project project)
   at MsBuildTaskExplorer.SolutionInfo.BuildMsBuildTask(String fullPath) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 130
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(DirectoryInfo directory) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 104
   at MsBuildTaskExplorer.SolutionInfo.<GetMsBuildTasks>b__21_0(List`1 current, DirectoryInfo dir) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 94
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(DirectoryInfo directory) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 90
   at MsBuildTaskExplorer.SolutionInfo.<GetMsBuildTasks>b__21_0(List`1 current, DirectoryInfo dir) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 94
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(DirectoryInfo directory) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 90
   at MsBuildTaskExplorer.SolutionInfo.<GetMsBuildTasks>b__21_0(List`1 current, DirectoryInfo dir) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 94
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(DirectoryInfo directory) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 90
   at MsBuildTaskExplorer.SolutionInfo.<GetMsBuildTasksAsync>b__20_0() in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 85
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsBuildTaskExplorer.ViewModels.TaskExplorerViewModel.<UpdateTaskList>d__31.MoveNext() in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\ViewModels\TaskExplorerViewModel.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsBuildTaskExplorer.ViewModels.ViewModelFactory.ExceptionInterceptor.<InternalInterceptAsynchronous>d__2.MoveNext() in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\ViewModels\ViewModelFactory.cs:line 60
```

## I have several projects unloaded in my solution. That might be culprit ?

**: this is the succession of actions I took, as close as I can remember them:
- opened several menus, tabs and dialogs while trying to find the `MSBuildTaskExplorer`,
- tried clicking on the Settings button in MSBuild, but it didn't work anymore,
- restarted VS,
- opened MSBuild again, the filter text was back. I erased it. After clicking refresh twice, the list refreshed with the targets for just a second or so

**Comment by alexis-** [comment] 2020-02-13 16:13
I reloaded **MSBuild Task Explorer** and the targets are now displaying:

![image](https://user-images.githubusercontent.com/3876562/74454320-fff2b580-4e83-11ea-8fe1-49d9b781b384.png)

The tasks appear to be running as intended. I will let you know if irregular behaviour shows up again.

**Comment by Serg046** [comment] 2020-02-13 16:23
Regarding the exception. On my side I see more clear one:

```
Exception: Microsoft.Build.Exceptions.InvalidProjectFileException
The project "C:\Tests\SuperMemoAssistant\src\Services\SuperMemoAssistant.Services.Medias.Images\SuperMemoAssistant.Services.Medias.Images.csproj" was not loaded.
The imported project "C:\Tests\SuperMemoAssistant\libs\pngcs\pngcs.projitems" was not found. Confirm that the expression in the Import declaration "..\..\..\libs\pngcs\pngcs.projitems" is correct, and that the file exists on disk.  C:\Tests\SuperMemoAssistant\src\Services\SuperMemoAssistant.Services.Medias.Images\SuperMemoAssistant.Services.Medias.Images.csproj
Stack trace:
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at MsBuildTaskExplorer.SolutionInfo.BuildMsBuildTask(String fullPath) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 125
   at MsBuildTaskExplorer.SolutionInfo.GetMsBuildTasks(DirectoryInfo directory) in C:\Projects\MsBuildTaskExplorer\MsBuildTaskExplorer\SolutionInfo.cs:line 104
```
The thing is that it doesn't work in VS itself as well. Anyway, it doesn't produce any problems, just litters the output. Since the original issue is not reproducible now, I'm closing the ticket for now.

**Closed as completed by Serg046** 2020-02-13 16:23 UTC
